name: Java CI with Gradle

on:
  pull_request:
    branches: [ 'develop' ]

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'


    - name: Create application.yml
      run: |
        echo "${{ secrets.APPLICATION_YML }}" > src/main/resources/application.yml

    - name: Set yml file
      uses: microsoft/variable-substitution@v1
      with:
        files: ./src/main/resources/application.yml, ./src/main/resources/application-gcs.yml
      env:
        spring.datasource.driver-class-name: ${{ secrets.BUILD_DATASOURCE_DRIVER_CLASS_NAME }}
        spring.datasource.url: ${{ secrets.BUILD_DATASOURCE_URL }}
        spring.jpa.hibernate.ddl-auto: ${{ secrets.BUILD_JPA_DDL_AUTO }}

        server.port: ${{ secrets.SERVER_PORT }}
        server.ssl.key-store-password: ${{ secrets.KEYSTORE_PASSWORD }}

        jwt.secret: ${{ secrets.JWT_SECRET }}

        spring.cloud.gcp.storage.credentials.location: ${{ secrets.GCS_KEY_LOCATION }}
        spring.cloud.gcp.storage.project-id: ${{ secrets.GCS_PROJECT_ID }}
        spring.cloud.gcp.storage.bucket-name: ${{ secrets.GCS_BUCKET_NAME }}
        spring.cloud.gcp.storage.bucket-dir: ${{ secrets.GCS_BUCKET_DIR }}
        spring.cloud.gcp.storage.key-name: ${{ secrets.GCS_KEY_NAME }}


    - name: Create-json
      id: create-json
      uses: jsdaniell/create-json@v1.2.2
      with:
        name: ${{ secrets.GCS_KEY_NAME }}
        json: ${{ secrets.GCS_KEY_JSON }}
        dir: ${{ secrets.GCS_KEY_DIR_LOCATION }}

    - name: Keystore Save
      run: echo "${{ secrets.KEYSTORE }}" | base64 --decode > ./src/main/resources/keystore.p12

    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build